Enable pipefail in build-lcg-cvmfs workflow (valgrind job)
Added pipefail option to ensure script fails on errors.

diff --git a/.github/workflows/build-lcg-cvmfs.yml b/.github/workflows/build-lcg-cvmfs.yml
--- a/.github/workflows/build-lcg-cvmfs.yml
+++ b/.github/workflows/build-lcg-cvmfs.yml
@@ -391,6 +391,9 @@ jobs:
         with:
           release-platform: ${{ matrix.release }}/${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.opt }}
           run: |
+            # Ensure we fail even when piping output to tee
+            set -o pipefail
+
             echo "::group::System architecture"
             gcc -march=native -Q --help=target | grep -m1 -- '-march='
             echo "::endgroup::"
